# -*- coding: utf-8 -*-
"""
Created on Tue Dec 02 17:30:25 2014
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%  Driver for the optimizer ECDFO.
%  ECDFO can solve a minimization problem of the form
%
%      minimize     f(x)
%      subject to   lx <=   x   <= ux
%                   li <= ci(x) <= ui
%                   ce(x) == 0,
%
%  where f: Rn -> R (hence x is the vector of n variables to optimize),
%  lx and ux are lower and upper bounds on x, ci: Rn -> Rmi, li and ui
%  are lower and upper bounds on ci(x), and ce: Rn -> Rme.
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
@author: jaco_da
"""

# Autogenerated with SMOP version 
# c:\Users\jaco_da\AppData\Local\Continuum\Anaconda\Scripts\smop-script.py run_ecdfo.m

#from __future__ import division
#try:
import helper
from runtime import *
from ecdfo_init_prob import ecdfo_init_prob_
from ecdfo_global_variables import set_prob, set_threshold,get_prob
from ecdfo import ecdfo_
from evalfgh import evalfgh_
#except ImportError:
#from smop.runtime import *


#clear(char('all'))
#close(char('all'))
#_format(char('long'))
#global n,nb,mi,me,prob,threshold

set_prob(3)
prob=get_prob()
options = helper.dummyUnionStruct()
options.tol=matlabarray([])

x,lx,ux,dxmin,li,ui,dcimin,infb,n,nb,mi,me,info=ecdfo_init_prob_(prob,nargout=13)
lb=zeros_(1,n)
ub=zeros_(1,n)
lb[arange_(1,n)]=lx
ub[arange_(1,n)]=ux
if mi:
    lb[arange_(n + 1,n + mi)]=li
    ub[arange_(n + 1,n + mi)]=ui
set_threshold(1e-08)
options.algo_method='quasi-Newton'
options.algo_globalization='trust regions'
options.hess_approx='model'
options.bfgs_restart=0
options.algo_descent='Powell'
if nb + mi + me == 0:
    options.algo_descent='Wolfe'
options.tol[1]=1e-05
options.tol[2]=1e-05
options.tol[3]=1e-05
options.dxmin=dxmin
options.miter=500
options.msimul=500
options.verbose=2
lm=matlabarray([])
x,lm,info=ecdfo_(evalfgh_,x,lm,lb,ub,options,nargout=3)
print x



#clear(char('all'))
#close(char('all'))
#_format(char('long'))
#global n,nb,mi,me,prob,threshold
#prob=4
#x,lx,ux,dxmin,li,ui,dcimin,infb,n,nb,mi,me,info=ecdfo_init_prob(prob,nargout=13)
#lb[arange_(1,n)]=lx
#ub[arange_(1,n)]=ux
#if mi:
#    lb[arange_(n + 1,n + mi)]=li
#    ub[arange_(n + 1,n + mi)]=ui
#threshold=1e-08
#options.algo_method=char('quasi-Newton')
#options.algo_globalization=char('trust regions')
#options.hess_approx=char('model')
#options.bfgs_restart=0
#options.algo_descent=char('Powell')
#if nb + mi + me == 0:
#    options.algo_descent=char('Wolfe')
#options.tol[1]=1e-05
#options.tol[2]=1e-05
#options.tol[3]=1e-05
#options.dxmin=dxmin
#options.miter=500
#options.msimul=500
#options.verbose=2
#lm=[]
#x,lm,info=ecdfo(evalfgh,x,lm,lb,ub,options,nargout=3)
#x
